#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
module load samtools bowtie2 boost tophat 
module unload anaconda3 python2 
module load python3 R rseqc

geneBody_coverage.py -r /project/bf528/project_2/reference/annot/mm9.bed -i /projectnb/bf528/users/group_5/project_2/programmer/accepted_hits.bam -o /projectnb/bf528/users/group_5/project_2/programmer/output/genebody

# inner_distance.py -r /project/bf528/project_2/reference/annot/mm9.bed -i /projectnb/bf528/users/group_5/project_2/programmer/accepted_hits.bam -o /projectnb/bf528/users/group_5/project_2/programmer/output/innerdistance

bam_stat.py -i /projectnb/bf528/users/group_5/project_2/programmer/accepted_hits.bam
 
echo "Job finished: $(date +%F)"
